version: '2'

services:
  openldap:
    image: osixia/openldap:1.5.0
    ports:
      - 389:389
    hostname: openldap
    container_name: openldap
    environment:
      LDAP_ORGANISATION: Demo
      LDAP_DOMAIN: example.org
      LDAP_BASE_DN: dc=example,dc=org
    volumes:
      - ./ldap_users:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: "--copy-service"
