version: '2'

services:
  openldap:
    image: osixia/openldap:1.5.0
    ports:
      - 389:389
    hostname: openldap
    container_name: openldap
    environment:
      LDAP_ORGANISATION: example
      LDAP_DOMAIN: example.org
      LDAP_BASE_DN: dc=example,dc=org
    command: "--copy-service"
    volumes:
      - ./ldap_users:/container/service/slapd/assets/config/bootstrap/ldif/custom

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    ports:
      - 8080:80
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: false
